sudo: false
language: rust
rust:
  - nightly
  - beta
  - 1.11.0

install:
  - rvm use 2.2
  - bundle install --path vendor/bundle

script:
  - bundle exec fluentd -c conf/in_forward.conf &
  - cargo test --features "readme-testing fluentd"

after_script:
  - killall ruby
