version: '{build}'
os:
  - Visual Studio 2015
environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64
      RUSTVER: 1.11.0
      ruby_version: "23-x64"
      devkit: C:\Ruby23-x64\DevKit
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64
      RUSTVER: 1.11.0
      ruby_version: "23"
      devkit: C:\Ruby23\DevKit

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUSTVER}-${env:TARGET}.exe"
  - rust-%RUSTVER%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - "%devkit%\\devkitvars.bat"
  - ruby --version
  - bundle install

build: false

test_script:
  - cmd: start /b bundle exec fluentd -c .\conf\in_forward.conf
  - cargo test --features "readme-testing fluentd"

after_test:
  - taskkill /F /IM ruby.exe
