[package]
name = "fruently"
version = "0.1.1"
authors = ["Hiroshi Hatake <cosmo0920.wp@gmail.com>"]
description = "A yet another Fluentd logger for Rust."
license-file = "LICENSE"
repository = "https://github.com/cosmo0920/fruently"

[features]
fluentd = []

[dependencies]
rustc-serialize = "~0.3.18"
time = "~0.1.34"
retry = "~0.3.0"